### ISSUE TITLE
`No such file or directory: '/home/***/proabc2-work/session.log`

### ISSUE THREAD

**Issue by AbDiscover** [haddocking/proABC-2#14]
I used docker as " docker run ghcr.io/haddocking/proabc-2:latest /home/***/proabc2-work h.fasta l.fasta", however, the error cames"[Errno 2] No such file or directory: '/home/***/proabc2-work/session.log".  May I have your advice on this？

**Comment by rvhonorato** [comment]
From your command it seems that you are missing the `-v` flag;

```
docker run \
    ghcr.io/haddocking/proabc-2:latest \
    -v `pwd`:/data \ ## This line
    /home/user/proabc2-work h.fasta l.fasta
```

you might need to adjust the paths to your case

**Comment by AbDiscover** [comment]
“yilu@localhost:~/proabc2-work$ docker run ghcr.io/haddocking/proabc-2:latest -v /home/yilu/proabc2-work h.fasta l.fasta
usage: proabc2 [-h] folder heavy light
proabc2: error: unrecognized arguments: -v” It seems that “-v” can be recognized

**Comment by rvhonorato** [comment]
The `-v` goes inside the docker arguments, try this:

Go into your home directory
```bash
cd /home/yilu
```

Run the command:
```bash
docker run \
  -v `pwd`:/data
  ghcr.io/haddocking/proabc-2:latest \
  proabc2-work h.fasta l.fasta
```

**Comment by AbDiscover** [comment]
***@***.***:~$ docker run ghcr.io/haddocking/proabc-2:latest -v 'pwd':/data /home/yilu/proabc2-work h.fasta l.fasta
usage: proabc2 [-h] folder heavy light
proabc2: error: unrecognized arguments: -v l.fasta”
At the same time，I tried “pip install” method，however, it was stopped as "ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from proabc-2) (from versions: 2.2.0 ..."
The environement is based on Windows 11+WSL2+Docker-Desktop(win)+ubuntu20.04.
________________________________
发件人: Rodrigo Vargas Honorato ***@***.***>
发送时间: 2024年6月6日 17:51
收件人: haddocking/proABC-2 ***@***.***>
抄送: AbDiscover ***@***.***>; Author ***@***.***>
主题: Re: [haddocking/proABC-2] [Errno 2] No such file or directory: '/home/***/proabc2-work/session.log". (Issue #14)


The -v goes inside the docker arguments, try this:

Go into your home directory

cd /home/yilu

Run the command:

docker run \
  -v `pwd`:/data
  ghcr.io/haddocking/proabc-2:latest \
  proabc2-work h.fasta l.fasta

―

**Comment by Iqrarshad** [comment]
I am experiencing the same issue. Kindly let me know how to resolve this issue

**Comment by rvhonorato** [comment]
Could you please share what command you tried to input?

**Comment by Iqrarshad** [comment]
**docker run --rm -v C:/Users/Admin/proabc2-prediction:/data ghcr.io/haddocking/proabc-2:latest proabc2-prediction/ heavy.fasta light.fasta** I am trying this command

**Comment by Iqrarshad** [comment]
This command
**docker run --rm -v C:/Users/Admin/proabc2-prediction:/data ghcr.io/haddocking/proabc-2:latest proabc2-prediction/ heavy.fasta light.fasta**

**Comment by rvhonorato** [comment]
Thanks @Iqrarshad, indeed with powershell/cmd i'm also getting this error. Could you instead try via WSL and check if that works for you?

**Comment by Iqrarshad** [comment]
My issue has been resolved. The folder we created earlier, "proabc2-prediction," required permission to write a log file. I updated the permissions of the folder, and it worked for me.

**Comment by rvhonorato** [comment]
Thanks for the update on the workaround 👍🏽

**Comment by PCRandChill** [comment]
Hey - I'm running the following command
```
docker run \
  -v `pwd`:/data \
  ghcr.io/haddocking/proabc-2:latest \
  proabc2-prediction/ heavy.fasta light.fasta
```
 and I still have the following error:
[Errno 2] No such file or directory: 'proabc2-prediction/session.log' 

The tried the permission fix and I have all permissions for "proabc2-prediction" directory. However the error persists.
`ls -l
drwxrwxrwx   2 root root    4096 Feb  5 10:35 proabc2-prediction
`

**Comment by rvhonorato** [comment]
@PCRandChill could you please post here the full error and try running this command instead?

```
docker run \
  --rm \
  --user $(id -u):$(id -g) \
  -v `pwd`:/data \
  ghcr.io/haddocking/proabc-2:latest \
  proabc2-prediction/ heavy.fasta light.fasta
```

**Comment by PCRandChill** [comment]
@rvhonorato Thanks for the reply. I figured out my problem was in the directory creation. My top level directory is proabc2-prediction and I have the two .fasta files in there. So, when I mount this directory to the /data directory of the container only the files inside we mounted essentially making the next call ` proabc2-prediction/ heavy.fasta light.fasta` invalid. I modified it as below and it works.
`docker run \
  -v /home/brookt/proabc2-prediction:/data \
  ghcr.io/haddocking/proabc-2:latest \
  /data heavy.fasta light.fasta`

**Comment by PCRandChill** [comment]
@rvhonorato Thanks for the reply. I figured out my problem was in the directory creation. My top level directory is proabc2-prediction and I have the two .fasta files in there. So, when I mount this directory to the /data directory of the container only the files inside we mounted essentially making the next call`  proabc2-prediction/ heavy.fasta light.fasta `invalid. I modified it as below and it works.
`docker run \
 -v /home/user/proabc2-prediction:/data \
 ghcr.io/haddocking/proabc-2:latest \ 
/data heavy.fasta light.fasta`

**Comment by rvhonorato** [comment]
Thanks for the update - we will think of a execution script to facilitate execution and avoid these issues.
